USE customer_behaviour;

SELECT * FROM customer LIMIT 20;

-- 1 WHAT IS THE TOTAL REVENUE GENERATED BY MALE VS FEMALE CUSTOMERS?
SELECT gender,sum(purchase_amount) as revenue 
from customer
group by gender;

-- 2 which customers used a discount bill but still spsnt more than the average purchase amount?
select customer_id,purchase_amount 
from customer
where discount_applied = 'Yes' and purchase_amount >=(select avg(purchase_amount) from customer);

-- 3 which are the top 5 products with the highest rating review
select item_purchased, round(avg(review_rating),2)
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- 4 Compare the avg btween standard and express shipping
-- if ecpress is more the business should focus on faster shipping

select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ("Standard","Express")
group by shipping_type;

-- 5 do subscribers spent more compare avg spent and total revenue &&& and cmpr this between subscrbd vs non subscrbd
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spent,
round(avg(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,average_spent desc;

-- 6 which 5 products have the highest percentage of purchase with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied = "Yes" then 1 else 0 end) / count(*),2) as discount_rate_per_item_type
from customer
group by item_purchased
order by discount_rate_per_item_type desc
limit 5;

-- 7 segment the customers into new,returning and loyal based on their total
-- number of previous purchases and show the count of each segment
with customer_type as
( select customer_id,previous_purchases,
CASE 
	WHEN previous_purchases=1 THEN "New"
    WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
    ELSE "Loyal"
    END AS customer_segment
from customer 
) 
select customer_segment,count(*) as "Number of costomers"
from customer_type
group by customer_segment;
    
-- 8 what are the top 3 most purchased product in each category
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

-- 9 are customers who are repeat buyers more than 5 prev purchases also likely to subscribe 
select subscription_status,
count(customer_id) as repeat_buyers 
from customer 
where previous_purchases > 5
group by subscription_status;

-- 10 what is the revenue contribution for each age group?
select age_grp,
sum(purchase_amount) as total_rev
from customer 
group by age_grp
order by total_rev desc; 

